# PostgreSQL
PG_USERNAME: str = ...
PG_PASSWORD: str = ...
PG_HOST: str = ...
PG_PORT: int = ...
PG_DB_NAME: str = ...

# MongoDB
MONGO_USERNAME: str = ...
MONGO_PASSWORD: str = ...
MONGO_HOST: str = ...
MONGO_PORT: int = ...
MONGO_DB_NAME: str = ...

# MinIO
MINIO_ACCESS_KEY: str = ...
MINIO_SECRET_KEY: str = ...
MINIO_HOST: str = ...
MINIO_PORT: int = ...
